Error
"HTTPConnectionPool(host='host.docker.internal', port=8000): Max retries exceeded with url: /api/fct_mid_land_Status_forecast/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e46487150>: Failed to establish a new connection: [Errno 111] Connection refused'))"
